server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: cc.mrbird.febs.system.entity,cc.mrbird.febs.generator.entity,cc.mrbird.febs.job.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
#账号 密码  权限
# mrbird  1234qwer  超级管理员，拥有所有增删改查权限
# scott 1234qwer  注册账户，拥有查看，新增权限（新增用户除外）和导出Excel权限
# micaela 1234qwer  系统监测员，负责整个系统监控模块
# Jana  1234qwer  跑批人员，负责任务调度跑批模块